config/routes.rb
Mappo::Application.routes.draw do
  
  root to: 'pages#home'
  
  devise_for :users
  resources :users

  resources :locations
    
  resources :projects 

  match '/howto', to: 'pages#howto'
  match '/home', to: 'pages#home'
  match '/locations/:id/projects_of', to: 'locations#projects_of', :as => :projects_of
  

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  project_id      :integer
#  title           :string(255)
#  title_orig_lang :string(255)
#  summary         :text
#  channel         :string(255)
#  amount          :string(255)
#  implementer     :string(255)
#  cluster         :string(255)
#  npp             :string(255)
#  status          :string(255)
#  provinces       :string(255)
#  start_date      :date
#  end_date        :date
#  objective       :text
#  results         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gmaps_location  :string(255)
#

class Project < ActiveRecord::Base
  attr_accessible :amount, :channel, :cluster, :end_date, :implementer, :npp, :objective, :project_id, :provinces, :results, :start_date, :status, :summary, :title, :title_orig_lang
  attr_accessible :gmaps_location
  attr_accessible :locations, :location_ids, :location_attributes

  has_many :location_projects
  has_many :locations, :through => :location_projects
  accepts_nested_attributes_for :locations
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    @json=@project.locations.to_gmaps4rails do |location, marker|
      marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location})
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @project.locations.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])

  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    params[:project][:location_ids] ||= []

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="hero-unit">
  <div class="field">
    <%= f.label :project_id, "Project ID"%>
    <%= f.number_field :project_id %>
  </div>
  <br />
  <div class="field">
    <%= f.label :title, "Project title"%>
    <%= f.text_field :title %>
  </div>
  <br />
  <div class="field">
    <%= f.label :title_orig_lang, "Project title in original language" %>
    <%= f.text_field :title_orig_lang %>
  </div>
  <br />
  <div class="field">
    <%= f.label :summary %>
    <%= f.text_area :summary%>
  </div>
  <br />
  <div class="field">
    <%= f.label :channel %>
    <%= f.text_field :channel %>
  </div>
  <br />
  <div class="field">
    <%= f.label :amount, "Commitment Amount (euro)"%>
    <%= f.number_field :amount %>
  </div>
  <br />
  <div class="field">
    <%= f.label :implementer %>
    <%= f.text_field :implementer %>
  </div>
  <br />
  <div class="field">
    <%= f.label :cluster %>
    <%= f.text_field :cluster %>
  </div>
  <br />
  <div class="field">
    <%= f.label :npp, "NPP" %>
    <%= f.text_field :npp %>
  </div>
  <br />
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <br />
  <div class="field">
    <%= f.label :provinces %>
    <%= f.text_field :provinces %>
  </div>
  <div>
    <%=f.label :locations, "Mappable Locations"%>
    <ul class="checkbox-grid">
    <% for location in Location.find(:all, :order => :name) %>
      <li>
        <%= check_box_tag "project[location_ids][]", location.id, @project.locations.include?(location) %>
        <%= location.name %>
    <% end %>
    </ul>
    <div align="right">
      <%= link_to "+ New Location", new_location_path %>
    </div>
  </div>
  <br />
  <div class="field">
    <%= f.label :start_date, "Starting date"%> 
    <!--<%= f.date_select :start_date%>-->
    <%= f.text_field :start_date, :class => 'datepicker'%>
 </div>
  <br />
  <div class="field">
    <%= f.label :end_date, "Ending date"%>
<!--<%= f.date_select :end_date%>-->
  <%= f.text_field :end_date, :class => 'datepicker'%>
  </div>
  <br />
  <div class="field">
    <%= f.label :objective %>
    <%= f.text_area :objective %>
  </div>
  <br />
  <div class="field">
    <%= f.label :results, "Results / Activities" %>
    <%= f.text_area :results %>
  </div>

  </br>
  </br>
  <div class="actions">
    <%= f.submit %>
  </div>
</div><!-- form -->
<% end %>

app/views/projects/_new_form.html.erb
<hr />
<p>Create New Location</p>
<%= form_for(@project) do |f| %>
	<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :locations do |builder| %>
  	<div>
      <%= builder.label :name %><br />
      <%= builder.text_field :name %>
    </div>

    <div>
      <%= builder.label :state %><br />
      <%= builder.text_field :state %>
    </div>
  <% end %>
  <div>
    <%= f.submit 'Create'%>
  </div>
<% end %>
<hr />

app/views/projects/_new_loc_nested_form.html.erb
<hr />
<p>Create New Location</p>
<%= form_for(@project) do |f| %>
	<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :locations do |builder| %>
  	<div>
      <%= builder.label :name %><br />
      <%= builder.text_field :name %>
    </div>

    <div>
      <%= builder.label :country %><br />
      <%= builder.text_field :country %>
    </div>
  <% end %>
  <div>
    <%= f.submit 'Create'%>
  </div>
<% end %>
<hr />

app/views/projects/edit.html.erb
<% provide(:title, "Edit project") %>
<h1>Edit project</h1>

<div class="row">
	<%= render 'form' %>
</div>

<%= link_to 'Show', @project %> |
<%= link_to "Back", :back %>

app/views/projects/index.html.erb
<% provide(:title, 'Listing all projects') %>

<h1>Listing all projects</h1>
<div class="hero-unit">
<table class="table">
  <tr>
    <th>Project ID</th>
    <th>Project Title</th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.project_id %></td>
    <td><%= link_to project.title, project %></td>
    <% if user_signed_in? %>
    <td><%= link_to "Edit", edit_project_path(project) %></td>
    <td><%= link_to "Delete", project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

</table>
<% if user_signed_in? %>
<%= link_to '+ Add Project', new_project_path %>
<% end %>
</div>
<br />
<%= link_to "Back", :back %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<h2><%= @project.title %></h2>

<div class="hero-unit">
<div class="center">
<div id="map_canvas">
  <%= 
  if @project.locations!=[] 
    gmaps("markers" => {"data" => @json}, "map_options" => {"processing" => "json", "auto_zoom" => false, "zoom" => 6})
    else
      "<No locations found>"
    end %>
</div>
</div>


</br>
</br>
<p>
  <b>Project ID:</b>
  <%= @project.project_id %>
</p>

<p>
  <b>Project title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Project title in original language:</b>
  <%= @project.title_orig_lang %>
</p>

<p>
  <b>Summary:</b>
  <%= @project.summary %>
</p>

<p>
  <b>Channel:</b>
  <%= @project.channel %>
</p>

<p>
  <b>Commitment Amount (euro):</b>
  <%= @project.amount %>
</p>

<p>
  <b>Implementer:</b>
  <%= @project.implementer %>
</p>

<p>
  <b>Cluster:</b>
  <%= @project.cluster %>
</p>

<p>
  <b>NPP:</b>
  <%= @project.npp %>
</p>

<p>
  <b>Status:</b>
  <%= @project.status %>
</p>

<p>
  <b>Provinces:</b>
  <%= @project.provinces %>
</p>

<p>
  <b>Starting date:</b>
  <%= 
  if @project.start_date!=nil
  @project.start_date.strftime("%d/%m/%Y")
  end 
  %>
</p>

<p>
  <b>Ending date:</b>
  <%= 
  if (@project.end_date!=nil)
    @project.end_date.strftime("%d/%m/%Y")
  end 
  %>
</p>

<p>
  <b>Objective:</b>
  <%= @project.objective %>
</p>

<p>
  <b>Results/Activities:</b>
  <%= @project.results %>
</p>
</div>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>