config/routes.rb
Mappo::Application.routes.draw do
  
  root to: 'pages#home'
  
  devise_for :users
  resources :users

  resources :locations
    
  resources :projects 

  match '/howto', to: 'pages#howto'
  match '/home', to: 'pages#home'
  match '/locations/:id/projects_of', to: 'locations#projects_of', :as => :projects_of
  

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  country    :string(255)
#  latitude   :float
#  longitude  :float
#  gmaps      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
	acts_as_gmappable
  attr_accessible :gmaps, :latitude, :longitude, :name, :country
  
  has_many :location_projects
  has_many :projects, :through => :location_projects

  validates :country, :presence => true
  validates :name, :presence => true

  def gmaps4rails_address
  		"#{name}, #{country}"
  end

  #def gmaps4rails_infowindow
 	#	"<p>#{name}, #{country}</p>"
  #end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :projects_of]
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @sorted_locations = Location.find(:all, :order => :name)
    @json = @locations.to_gmaps4rails do |location, marker|
      marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @json = Location.find(params[:id]).to_gmaps4rails do |location, marker|
      marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location})
      marker.title "#{location.name}"
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  #GET /locations/1/projects_of
  def projects_of
    @location=Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hero-unit">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
    <br />
    <div> - Google Maps will set the following parameters automatically (if empty) - </div>
    <br />
    <div class="field">
     <%= f.label :latitude %>
      <%= f.text_field :latitude %>
   </div>
    <div class="field">
      <%= f.label :longitude %>
      <%= f.text_field :longitude %>
    </div>
    </div>
  <br />
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/locations/_infowindow.html.erb
<div align="center">
	<h4> <%= "#{location.name} #{location.country}" %> </h4>
	<p> number of projects: <%=location.projects.length%>  </p>
	<%= link_to  "<button class='btn'>show projects</button>".html_safe, location%>
	<!--
	projects_of_url(:id => location.id)
-->
</div>

app/views/locations/_listprojloc.html.erb
<table class="table">
  <tr>
    <th>Project ID</th>
    <th>Project Title</th>
    <th></th>
    <th></th>
  </tr>

<% @location.projects.each do |project| %>
  <tr>
    <td><%= project.project_id %></td>
    <td><%= link_to project.title, project %></td>
  </tr>
<% end %>

</table>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to "Back", :back %>

app/views/locations/index.html.erb
<% provide(:title, 'Listing locations') %>
<h1>Listing locations</h1>

<div class="hero-unit">
  <div id="map_canvas" align=center>
  <%= gmaps4rails(@json) %>
  </div>
  <br />
<table class="table ">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Projects</th>
    <th></th>
    <th></th>
  </tr>

<% @sorted_locations.each do |location| %>
  <tr>
    <td><%= link_to location.name, location %></td>
    <td><%= location.country %></td>
    <td><%= location.projects.length%></td>
    <% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<% if user_signed_in? %>
<%= link_to '+ New Location', new_location_path %>
<% end %>
</div>

<br />
<%= link_to "Back", :back %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/locations/projects_of.html.erb
<% provide(:title, 'Listing projects') %>

<h1>Projects in <%= @location.name %></h1>
<p>
  <b>
  Projects found:
  </b>
   <%=@location.projects.length%>
</p>
<div class="hero-unit">
  <%= render 'listprojloc' %>

</div>

<br />
<%= link_to "Back", :back %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @location.name %></h1>

<div class="hero-unit">
<table class="table table-condensed table-bordered">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Projects</th>
  </tr>


  <tr>
    <td><%= @location.name %></td>
    <td><%= @location.country %></td>
    <td><%= @location.projects.length%></td>
  </tr>

</table>

<div class="center">
<div id="map_canvas">
  <%= gmaps("markers" => {"data" => @json}, "map_options" => {"processing" => "json", "auto_zoom" => false, "zoom" => 6}) %>
</div>
</div>

<br />
<br />
<h4 align='center'>Projects in <%= @location.name %></h4>

  <%= render 'listprojloc' %>

</div>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Delete', @location, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>