config/routes.rb
Mappo::Application.routes.draw do
  
  root to: 'pages#home'
  
  devise_for :users
  resources :users

  resources :locations
    
  resources :projects 

  match '/howto', to: 'pages#howto'
  match '/home', to: 'pages#home'
  match '/locations/:id/projects_of', to: 'locations#projects_of', :as => :projects_of
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "How To",  howto_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <%=render 'layouts/usernavigation'%>
        </ul>
        <ul class="nav pull-left">
          <li><%=link_to "Home", root_path%></li>
          <li><%=link_to "Projects", projects_path%></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <span class="article-sidebar-title">
      <h4>Menù</h4>
      <hr />
  </span>
  <ul class="nav">
    <li class="active"><a <%=link_to "Home", root_path%> </a> </li>
    <li><a> <%=link_to "All Projects", projects_path%> </a></li>
    <li><a> <%=link_to "All Locations", locations_path%> </a></li>
    <% if user_signed_in? %>
    <li><a> <%=link_to "New Location", new_location_path%> </a></li>
    <li><a> <%=link_to "New Project", new_project_path%> </a></li>
    <li><a> <%= link_to "Users", users_path %> </a></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_usernavigation.html.erb
<% if user_signed_in? %>
    
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign Up', new_user_registration_path %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span2">
            <%= render 'layouts/sidebar'%>
          </div>
          <div class="span10">
            <%= render 'layouts/messages' %>
            <%= yield %>
            <%= yield :scripts %>
            <%= render 'layouts/footer' %>
          </div>
        </div> <!--row-fluid -->
      </div>
    </div>
  </body>
</html>